---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
    dockerfile: ../Dockerfile.centos7.j2
    pre_build_image: false
  - name: centos8
    image: centos:8
    dockerfile: ../files/Dockerfile.centos8.j2
    pre_build_image: false
  - name: ubuntu
    image: pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
