---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: sbeliakou/centos:7-sudo
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
scenario:
  test_sequence:
    - destroy
    - create 
    - converge
    - destroy
